import {Calistoga,Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const montserrat = Montserrat({
  subsets:['latin'],
  weight:["100","200","300","400","500","600","700","800","900"]
})

const calistoga = Calistoga({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});



export const metadata = {
  title: "Vedashray",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  antialiased bg-[#f7f5f0]`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
